/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'
import { customInstance } from '../../lib/axios-instance'
import type { UploadAttachmentsResponse } from '.././model'

/**
 * @summary Upload attachments
 */
export const uploadAttachmentsControllerHandle = (formData: FormData) => {
  return customInstance<UploadAttachmentsResponse>({
    url: `/attachments`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
  })
}

export const getUploadAttachmentsControllerHandleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadAttachmentsControllerHandle>>,
    TError,
    FormData,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadAttachmentsControllerHandle>>,
  TError,
  FormData,
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadAttachmentsControllerHandle>>,
    FormData
  > = formData => {
    return uploadAttachmentsControllerHandle(formData)
  }

  return { mutationFn, ...mutationOptions }
}

export type UploadAttachmentsControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadAttachmentsControllerHandle>>
>

export type UploadAttachmentsControllerHandleMutationError = unknown

/**
 * @summary Upload attachments
 */
export const useUploadAttachmentsControllerHandle = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadAttachmentsControllerHandle>>,
    TError,
    FormData,
    TContext
  >
}): UseMutationResult<
  Awaited<ReturnType<typeof uploadAttachmentsControllerHandle>>,
  TError,
  FormData,
  TContext
> => {
  const mutationOptions =
    getUploadAttachmentsControllerHandleMutationOptions(options)

  return useMutation(mutationOptions)
}
