/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'
import { customInstance } from '../../lib/axios-instance'
import type { RegisterViewResponse } from '.././model'

/**
 * @summary Register a view on a product
 */
export const registerViewControllerHandle = (id: unknown) => {
  return customInstance<RegisterViewResponse>({
    url: `/products/${id}/views`,
    method: 'POST',
  })
}

export const getRegisterViewControllerHandleMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerViewControllerHandle>>,
    TError,
    { id: unknown },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerViewControllerHandle>>,
  TError,
  { id: unknown },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerViewControllerHandle>>,
    { id: unknown }
  > = props => {
    const { id } = props ?? {}

    return registerViewControllerHandle(id)
  }

  return { mutationFn, ...mutationOptions }
}

export type RegisterViewControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerViewControllerHandle>>
>

export type RegisterViewControllerHandleMutationError = undefined

/**
 * @summary Register a view on a product
 */
export const useRegisterViewControllerHandle = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerViewControllerHandle>>,
    TError,
    { id: unknown },
    TContext
  >
}): UseMutationResult<
  Awaited<ReturnType<typeof registerViewControllerHandle>>,
  TError,
  { id: unknown },
  TContext
> => {
  const mutationOptions =
    getRegisterViewControllerHandleMutationOptions(options)

  return useMutation(mutationOptions)
}
