/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query'
import { customInstance } from '../../lib/axios-instance'
import type {
  AuthenticateSellerBody,
  AuthenticateSellerResponse,
} from '.././model'

/**
 * @summary Get the seller access token
 */
export const authenticateSellerControllerHandle = (
  authenticateSellerBody: AuthenticateSellerBody
) => {
  return customInstance<AuthenticateSellerResponse>({
    url: `/sellers/sessions`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: authenticateSellerBody,
  })
}

export const getAuthenticateSellerControllerHandleMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authenticateSellerControllerHandle>>,
    TError,
    { data: AuthenticateSellerBody },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof authenticateSellerControllerHandle>>,
  TError,
  { data: AuthenticateSellerBody },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authenticateSellerControllerHandle>>,
    { data: AuthenticateSellerBody }
  > = props => {
    const { data } = props ?? {}

    return authenticateSellerControllerHandle(data)
  }

  return { mutationFn, ...mutationOptions }
}

export type AuthenticateSellerControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof authenticateSellerControllerHandle>>
>
export type AuthenticateSellerControllerHandleMutationBody =
  AuthenticateSellerBody
export type AuthenticateSellerControllerHandleMutationError = undefined

/**
 * @summary Get the seller access token
 */
export const useAuthenticateSellerControllerHandle = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authenticateSellerControllerHandle>>,
    TError,
    { data: AuthenticateSellerBody },
    TContext
  >
}): UseMutationResult<
  Awaited<ReturnType<typeof authenticateSellerControllerHandle>>,
  TError,
  { data: AuthenticateSellerBody },
  TContext
> => {
  const mutationOptions =
    getAuthenticateSellerControllerHandleMutationOptions(options)

  return useMutation(mutationOptions)
}
/**
 * @summary Sign out
 */
export const signOutControllerHandle = () => {
  return customInstance<void>({ url: `/sign-out`, method: 'POST' })
}

export const getSignOutControllerHandleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signOutControllerHandle>>,
    TError,
    void,
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof signOutControllerHandle>>,
  TError,
  void,
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {}

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof signOutControllerHandle>>,
    void
  > = () => {
    return signOutControllerHandle()
  }

  return { mutationFn, ...mutationOptions }
}

export type SignOutControllerHandleMutationResult = NonNullable<
  Awaited<ReturnType<typeof signOutControllerHandle>>
>

export type SignOutControllerHandleMutationError = unknown

/**
 * @summary Sign out
 */
export const useSignOutControllerHandle = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof signOutControllerHandle>>,
    TError,
    void,
    TContext
  >
}): UseMutationResult<
  Awaited<ReturnType<typeof signOutControllerHandle>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getSignOutControllerHandleMutationOptions(options)

  return useMutation(mutationOptions)
}
