/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import type { ChangeProductStatusResponseProductOwnerAvatar } from './changeProductStatusResponseProductOwnerAvatar'

export type ChangeProductStatusResponseProductOwner = {
  /** @nullable */
  avatar: ChangeProductStatusResponseProductOwnerAvatar
  email: string
  id: string
  name: string
  phone: string
}
