/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */

export interface CreateSellerBody {
  /**
   * Created in POST - /attachments
   * @nullable
   */
  avatarId: string | null
  /** Unique */
  email: string
  name: string
  password: string
  passwordConfirmation: string
  /** Unique */
  phone: string
}
