/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import type { CreateProductResponseProductOwnerAvatar } from './createProductResponseProductOwnerAvatar'

export type CreateProductResponseProductOwner = {
  /** @nullable */
  avatar: CreateProductResponseProductOwnerAvatar
  email: string
  id: string
  name: string
  phone: string
}
