/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import type { CreateProductResponseProductAttachmentsItem } from './createProductResponseProductAttachmentsItem'
import type { CreateProductResponseProductCategory } from './createProductResponseProductCategory'
import type { CreateProductResponseProductOwner } from './createProductResponseProductOwner'

export type CreateProductResponseProduct = {
  attachments: CreateProductResponseProductAttachmentsItem[]
  category: CreateProductResponseProductCategory
  description: string
  id: string
  owner: CreateProductResponseProductOwner
  priceInCents: number
  title: string
}
