/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import type { GetProductResponseProductAttachmentsItem } from './getProductResponseProductAttachmentsItem'
import type { GetProductResponseProductCategory } from './getProductResponseProductCategory'
import type { GetProductResponseProductOwner } from './getProductResponseProductOwner'
import type { ListAllSellerProductsControllerHandleStatus } from './listAllSellerProductsControllerHandleStatus'

export type GetProductResponseProduct = {
  attachments: GetProductResponseProductAttachmentsItem[]
  category: GetProductResponseProductCategory
  description: string
  status: ListAllSellerProductsControllerHandleStatus
  id: string
  owner: GetProductResponseProductOwner
  priceInCents: number
  title: string
}
