/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */

export type ListAllSellerProductsControllerHandleStatus =
  (typeof ListAllSellerProductsControllerHandleStatus)[keyof typeof ListAllSellerProductsControllerHandleStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListAllSellerProductsControllerHandleStatus = {
  available: 'available',
  sold: 'sold',
  cancelled: 'cancelled',
} as const
