/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import type { ListAllProductsControllerHandleStatus } from './listAllProductsControllerHandleStatus'

export type ListAllProductsControllerHandleParams = {
  page?: unknown
  status?: ListAllProductsControllerHandleStatus
  search?: unknown
}
