/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import type { ListAllSellerProductsResponseProductsItemAttachmentsItem } from './listAllSellerProductsResponseProductsItemAttachmentsItem'
import type { ListAllSellerProductsResponseProductsItemCategory } from './listAllSellerProductsResponseProductsItemCategory'
import type { ListAllSellerProductsResponseProductsItemOwner } from './listAllSellerProductsResponseProductsItemOwner'

export type ListAllSellerProductsResponseProductsItem = {
  attachments: ListAllSellerProductsResponseProductsItemAttachmentsItem[]
  category: ListAllSellerProductsResponseProductsItemCategory
  description: string
  status: 'available' | 'sold' | 'cancelled'
  id: string
  owner: ListAllSellerProductsResponseProductsItemOwner
  priceInCents: number
  title: string
}
