/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * MBA Marketplace API
 * API to manage MBA Marketplace
 * OpenAPI spec version: 1.0
 */
import type { RegisterViewResponseProduct } from './registerViewResponseProduct'
import type { RegisterViewResponseViewer } from './registerViewResponseViewer'

export interface RegisterViewResponse {
  product: RegisterViewResponseProduct
  viewer: RegisterViewResponseViewer
}
